# Site settings
title: 做点什么 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "这是我的博客"  # 一句话描述你的博客
baseurl: ""
url: "https://zhoubaohang.github.io"  # 此处填写你的博客地址 

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "emmmmmmm ......."

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# About/contact
owner: 
  name: "周宝航" # 填写作者信息：名字
  email: zbh12306@163.com # 填写作者信息：邮箱
  bio: "就是微小的工作" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: zhoubaohang
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "你的名字" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
